<a href="https://colab.research.google.com/github/ali786-1/Computational-Statistics/blob/main/Ali_786.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=int(input('coefficient of x^2'))
b=int(input('coefficient of x'))
c=int(input('constant'))
d=(b*b-4*a*c)
import cmath
s=(-b+cmath.sqrt(d))/2*a
r=(-b-cmath.sqrt(d))/2*a
r1=-b/2*a
if d<0:
  print('roots are imaginary')
  print(s,r)
if d>0:
  print(' roots are real')
  print(s,r)
if d==0:
  print('roots are equal')
  print(r1,r1)

In [ ]:
A=input() 
B=input() 
while true:

In [ ]:
import math
print(' neter a number')
a=int(input())
s=math.sqrt(a)
print(' the square root of given number:',s)

 neter a number
16
 the square root of given number: 4.0


In [ ]:
a=int(input('enterthe value '))
b=int(input('enter the value'))
s=input('enetr the operator')
if s=='+':
  print('a+b is:',a+b)
if s=='-':
  print('a-b is:',a-b)
if s=='*':
  print('a*b is',a*b)
if s=='/':
  print('a/b is :',a/b)      

enterthe value 3
enter the value6
enetr the operator*
a*b is 18


In [ ]:
a=int(input('enter the value'))
b=int(input('enter the value'))
print('a&b is :',a&b)
print('a^b is :',a^b)

enter the value2
enter the value8
a&b is : 0
a^b is : 10


In [ ]:
import calendar
year=int(input('enter the year :'))
month=int(input('enter the month'))
x=calendar.month(year,month)
print(x)

enter the year :2021
enter the month7
     July 2021
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [ ]:
def prime_number(n):
  c=0
  for i in range(2,n):
    if n%i==0:
      c=c+1
  if c==0:
    print('it is a prime')
  else:
    print('not a prime')
def armstrong(num):
  n=p=num
  c=0
  sum=0
  while(p!=0):
    c=c+1
    p=p//10
  while(n!=0):
    rem=n%10
    sum=sum+rem**c
    n=n//10
  if sum==num:
    print(' the number is armstrong')
  else:
    print('not an armstrong') 
def fact(n):
  fact=1
  for i in range(1,n+1):
    fact=fact*i
  return fact
def strong(n):
  m=n
  sum=0
  while n!=0:
     a=n%10
     sum=sum+fact(a)
     n=n//10
  if m==sum:
    print('strong')
  else:
    print('not a strong')  
def perfect(n):
  temp=n
  sum=0
  for i in range(1,1+n//2):
    sum=sum+i
  if sum==temp:
    print(temp)  
n=int(input('enter the number'))
perfect(n)       



enter the number6
6


In [ ]:
import math
a=int(input())
b=str(input())
print(math.sqrt(a))
print(math.log10(a))
print(math.sin(a))
print('the ascii value of str(b)',ord(b))
print('the ascii value of a is',chr(a))
print(type(a))
print(type(b))
print(id(a))
print(id(b))

2
d
1.4142135623730951
0.3010299956639812
0.9092974268256817
the ascii value of str(b) 100
the ascii value of a is 
<class 'int'>
<class 'str'>
94878421858848
140662940987696


In [ ]:
a=input('enter the sentence')
m=0
n=0
w=1
s=0
for char in a:
  if char>='A' and char<='Z':
    m=m+1
  elif char>='a' and char<='z':
    n=n+1
  elif char==' ':
    w=w+1
  elif char>='0' and char<='9':
    s=s+1
print('no of words are :',w)
print('no of upper digits lettrs aree :',m)
print('no of lower digits letter are :',n)
print('no of digits are :',s)          

enter the sentenceADKJ kjdf 23652
no of words are : 3
no of upper digits lettrs aree : 4
no of lower digits letter are : 4
no of digits are : 5


In [ ]:
a=input('enetr a sentence')
s=input('enter word to be searched')
l=a.split()
w=0
for i in l:
  if i==s:
    w=w+1
print('the occurance of the word ',w)    

enetr a sentencethe saikrishna is jaffa jaffa
enter word to be searchedjaffa
2


In [ ]:
def palindrome(s):
  o=list(s)
  r=o.copy()
  o.reverse()
  if o==r:
    print('palindrome')
  else:
    print('not a palimndrome')
s=input('enter a string')
palindrome(s)      

enter a stringaja
palindrome


In [ ]:
a=input('enter a sentence')
s=a.split()
t=[]
for i in s:
  if i not in t:
    t.append(i)
print(t)  

enter a sentenceking is always a king
['king', 'is', 'always', 'a']


In [ ]:
import math
def variance(data,ddof=0):
  n=len(data)
  mean=sum(data)/n
  print('the mean of the given ',mean)
  return sum((x-mean)**2 for x in data)/(n-ddof)
def st_dev(data):
  var=variance(data)
  dev=math.sqrt(var)
  print(var)
  return dev
data=(4,45,6,4,4,6,4) 
st_dev(data)




the mean of the given  10.428571428571429
199.95918367346937


14.14069247503351

In [ ]:


X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


for i in range(len(X)):
   
   for j in range(len(Y[0])):
       
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [ ]:
from numpy import *
matrix=array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
result=array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(matrix)):
  for j in range(len(result)):
    result[i][j]=matrix[j][i]

print('\nresult is\n ',result)    

 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

result is
  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
def insert_spec_position(x,ali,pos):
    return ali[:pos-1]+[x]+ali[pos-1:]
ali= [1,1,2,3,4,4,5,1]
print("Original list:") 
print(ali)
a=int(input('enter the position of the element ')) 
x=int(input('value of the element'))
result = insert_spec_position(x,ali,a)
print("\nAfter inserting an element at kth position in the said list:")
print(result)


Original list:
[1, 1, 2, 3, 4, 4, 5, 1]
enter the position of the element 5
value of the element344

After inserting an element at kth position in the said list:
[1, 1, 2, 3, 344, 4, 4, 5, 1]


In [ ]:
l={1:"game",2:"fun",3:"relax"}
print(l)
m=l.pop(2)
print(m)
print(" now the remAining in dictionary are:",l)
a={'s':"jaaanu"}
i=l.update(a)
print(l)
print(l.keys())
print(l.get('s'))
print(l.values())
print(l.items())

{1: 'game', 2: 'fun', 3: 'relax'}
game
fun
 now the remAining in dictionary are: {1: 'game', 3: 'relax'}
{1: 'game', 3: 'relax', 's': 'jaaanu'}
dict_keys([1, 3, 's'])
jaaanu
dict_values(['game', 'relax', 'jaaanu'])
dict_items([(1, 'game'), (3, 'relax'), ('s', 'jaaanu')])


In [ ]:

from math import factorial

n=int(input())
r=int(input())
ncr=factorial(n)//(factorial(r)*factorial(n-r))
print(ncr)
for i in range(n):
    for j in range(n-i+1):
        print(end=" ")
    for j in range(i+1):
        print(factorial(i)//(factorial(j)*factorial(i-j)), end=" ")
    print()

5
3
10
      1 
     1 1 
    1 2 1 
   1 3 3 1 
  1 4 6 4 1 


In [ ]:
A=input() 
B=input() 
while True:
    print(B) 
    Y=(B+A/B)*(0.5) 
    if Y==B:
       Break
    B=Y

25
3
3


TypeError: ignored

Python program to print array in reverse Order.

In [ ]:
l=list(map(int,input().split()))
print(l[::-1])

Write a program in Python to remove duplicate elements form array.

In [ ]:
l=list(map(int,input().split()))
k=[]
for i in l:
  if i not in k:
    k.append(i)
print(k)
# m=set(l)
# print(m)

 Write a program in Python to find second highest number in an integer array.

In [12]:
l=list(map(int,input().split()))
l.sort()
m=len(l)
print(l[m-2])


2 5 77 33 44 2 2 299
77


Write a program in Python to find largest and smallest number in array.

In [ ]:
l=list(map(int,input().split()))
l.sort()
print(l[0],l[len(l)-1])

Write a program in Python for, How to compare two array is equal in size or not.

In [ ]:
l=list(map(int,input().split()))
s=list(map(int,input().split()))
if len(l)==len(s):
  print("yes")
else :
  print('no')


Write a program in Python for, How to find all pairs in array of integers whose sum is equal to given number.

In [ ]:
l=list(map(int,input().split()))
n=int(input())
for i in range(len(l)):
  for j in range(i+1,len(l)):
    if l[i]+l[j]==n:
      print('(%d,%d)'%(l[i],l[j]))


Write a program in Python for, In a array 1-100 multiple numbers are duplicates, how do you find it.

In [21]:
l=list(map(int,input().split()))
k=[]
c=[]
for i in l:
  if i not in k:
    k.append(i)
  else:
    if i not in c:
      c.append(i)
print("Repeated elements are",c)

1 2 3 2 3 4 1 
Repeated elements are [2, 3, 1]


Write a program in Python for, In array 1-100 numbers are stored, one number is missing how do you find it.

In [35]:
l=list(map(int,input().split()))
for i in range(len(l)):
  j=i+1
  if j==len(l):
    break
  if (l[i]-l[j])!=-1:
    print(l[j]-1)



1 2 3 4 5 6 7 8 9 10 11 12 13 15 16 17 19
14
18


 Python program to remove given character from String.

In [61]:
s=input()
k=s.replace(input(),"")
print(k)

pavan
a
pvn


 Python Program to count occurrence of a given characters in string.

In [73]:
s=input()
l=list((s))
x=[]
for i in l:
  if i not in x:
    x.append(i)
    k=s.count(i)
    print(i,"occurred",k,"times")



pavaaa
p occurred 1 times
a occurred 4 times
v occurred 1 times


Python program to check a String is palindrome or not.

In [64]:
s=input()
if s==s[::-1]:
  print("yes")
else:
  print("No")

madam
yes


 Python program to check given character is vowel or consonant.

In [75]:
s=input()
for i in s:
  if i in ('a','e','i','o','u','A','E','I','O','U'):
    print(i,'is vowel')
  else:
    print(i,'"consonant")

ujjwal
u is vowel
j consonant
j consonant
w consonant
a is vowel
l consonant


Python program to count Occurrence Of Vowels & Consonants in a       String.

In [76]:
s=input()
v=0
c=0
for i in s:
  if i in ('a','e','i','o','u','A','E','I','O','U'):
    v=v+1
  else:
    c=c+1
print("vowels are ",v,"")



pavan
