<a href="https://colab.research.google.com/github/ali786-1/Computational-Statistics/blob/main/discriminent_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=int(input("Enter no of observations"))
x=[]
for i in range(n-1):
  k=list(map(float,input(f'enter {i+1} number').split()))
  x.append(k)
print(x)

Enter no of observations3
enter 1 number1 2 3 4 5 4 5 5 3 5 6
enter 2 number2 3 3 5 5 2 0 2 2 3 3
[[1.0, 2.0, 3.0, 4.0, 5.0, 4.0, 5.0, 5.0, 3.0, 5.0, 6.0], [2.0, 3.0, 3.0, 5.0, 5.0, 2.0, 0.0, 2.0, 2.0, 3.0, 3.0]]


In [ ]:
import numpy as np
# y=list(map(int,input().split()))
x=np.array(x)
print(x)
mu=[]
s=0
for i in range(len(x)):
  s=np.sum(x[i])
  mu.append(s/len(x[i]))
np.round(mu,2)
Mu=np.array(mu)
print(Mu)

[[1. 2. 3. 4. 5. 4. 5. 5. 3. 5. 6.]
 [2. 3. 3. 5. 5. 2. 0. 2. 2. 3. 3.]]
[3.90909091 2.72727273]


In [146]:
y=list(map(float,input().split()))
t=y.copy()

1 1 1 1 1 2 2 2 2 2 2


In [147]:
y=np.array(y)
l=len(x[0])
X=np.transpose(x)
l
X

array([[1., 2.],
       [2., 3.],
       [3., 3.],
       [4., 5.],
       [5., 5.],
       [4., 2.],
       [5., 0.],
       [5., 2.],
       [3., 2.],
       [5., 3.],
       [6., 3.]])

In [148]:
cat=[]
x1=[]
x2=[]
for i in y:
  if i not in cat:
    cat.append(i)
cat
for i in range(n-1):
  c=0
  for j in range(l):
    if y[j]==1:
      c=c+1
  row1=[]
  row2=[]
  for k in range(c):
    row1.append(x[i][k])
  for h in range(c,len(y)):
    row2.append(x[i][h])
  x1.append(row1)
  x2.append(row2)
print(x1)
print(x2)

    


[[1.0, 2.0, 3.0, 4.0, 5.0], [2.0, 3.0, 3.0, 5.0, 5.0]]
[[4.0, 5.0, 5.0, 3.0, 5.0, 6.0], [2.0, 0.0, 2.0, 2.0, 3.0, 3.0]]


In [149]:
mu1=[]
mu2=[]
for i in range(len(x1)):
  s=np.sum(x1[i])
  a=np.sum(x2[i])
  mu1.append(s/len(x1[i]))
  mu2.append(a/len(x2[i]))
print(np.round(mu1,2))
print(np.round(mu2,2))

[3.  3.6]
[4.67 2.  ]


In [ ]:
x_mu=X-Mu
x_mu 


array([[-2.90909091, -0.72727273],
       [-1.90909091,  0.27272727],
       [-0.90909091,  0.27272727],
       [ 0.09090909,  2.27272727],
       [ 1.09090909,  2.27272727],
       [ 0.09090909, -0.72727273],
       [ 1.09090909, -2.72727273],
       [ 1.09090909, -0.72727273],
       [-0.90909091, -0.72727273],
       [ 1.09090909,  0.27272727],
       [ 2.09090909,  0.27272727]])

In [ ]:
c=(np.dot(np.transpose(x_mu),x_mu))/l
c
c_inv=np.linalg.inv(c)
c_inv

array([[ 0.48327726, -0.04136157],
       [-0.04136157,  0.548585  ]])

In [144]:
print("Enter  elemets to predict ")
xk=list(map(float,input().split()))
XK=np.array(xk)
print(XK)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 


Enter  elemets to predict 
5.1 3.2
[5.1 3.2]


In [145]:
f=[]
muu=[mu1,mu2]
for i in range(n-1):
  f.append(np.dot(np.dot(muu[i],c_inv),np.transpose(xk)) - 0.5*np.dot(np.dot(muu[i],c_inv),np.transpose(muu[i]))+np.log(t.count(cat[i])/l))
np.round(f,2)
for i in range(n-1):
  print(f'F{i+1} value is {f[i]}')
if f[0]>f[1]:
  print("New entries belongs to first category")
else:
  print("New entries belongs to second category")


F1 value is 6.486040957466721
F2 value is 7.393771842052746
New entries belongs to second category
