<a href="https://colab.research.google.com/github/ali786-1/Computational-Statistics/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
#y=np.array(list(map(int,input().split())))
a=np.array(list(map(int,input().split())))
b=np.array(list(map(int,input().split())))
c=np.array(list(map(int,input().split())))
xt=np.array([a,b,c])
print(xt)
x=np.transpose(xt)
print(x)



1 1 1 1 1 1 1 1 1 1 1 1
9 8 7 14 12 10 7 4 6 5 7 6
62 58 64 60 63 57 55 56 59 61 57 60
[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 9  8  7 14 12 10  7  4  6  5  7  6]
 [62 58 64 60 63 57 55 56 59 61 57 60]]
[[ 1  9 62]
 [ 1  8 58]
 [ 1  7 64]
 [ 1 14 60]
 [ 1 12 63]
 [ 1 10 57]
 [ 1  7 55]
 [ 1  4 56]
 [ 1  6 59]
 [ 1  5 61]
 [ 1  7 57]
 [ 1  6 60]]


In [ ]:
r=np.dot(xt,x)
print(r)


[[   12    95   712]
 [   95   845  5663]
 [  712  5663 42334]]


In [ ]:
invxtx=np.linalg.inv(r)
print(invxtx)

[[ 4.08944026e+01  1.14046520e-01 -7.03043891e-01]
 [ 1.14046520e-01  1.17514524e-02 -3.49009300e-03]
 [-7.03043891e-01 -3.49009300e-03  1.23147269e-02]]
[40.8944026   0.11404652 -0.70304389]


In [ ]:
y=np.array(list(map(int,input().split())))


100 110 105 94 95 99 104 108 105 98 105 110


In [ ]:
xty=np.dot(xt,y)
xtyy=np.transpose(xty)
beta=np.dot(invxtx,xtyy)
print(beta)

[133.46048243  -1.24850346  -0.35100837]


In [ ]:
yi=beta[0]+beta[1]*b+beta[2]*c
print(yi)

[100.46143226 103.11396921 102.25642243  94.92093172  96.36491352
 100.96797067 105.41549778 108.80999978 105.25996775 105.80645446
 104.71348104 104.90895938]


In [ ]:
err=np.subtract(y,yi)
sse=np.sum(np.dot(err,err))
print(sse)
para_3={
    'observed':y.transpose(),
    'calculated':yi.transpose(),
    'error':(y-yi).transpose()
}

151.41040622031764


In [ ]:
ybar=np.mean(y)
SST=np.sum(np.square(np.subtract(y,ybar)))
SST

330.25

In [ ]:
SSr=SST-sse
SSr


178.83959377968236

In [ ]:
Coeff_det=SSr/SST
if Coeff_det>0.90:
  print('Accept')
else:
  print("reject")

reject


Anova


In [ ]:
k=3
n=12
f=(SSr/(k-1))/(sse/(n-k))
an={
    'source of variation':['regression','error','total'],
    'sum of squares':[SSr,sse,SST],
    'degree of freedom':[k-1,n-k,n-1],
    'mean sum of squares':[SSr/(k-1),sse/(n-k),''],
    'variance Ratio':['',f,'']
}

In [ ]:
a=pd.DataFrame(an)
d=pd.DataFrame(para_3)
print(a)
print(d)

  source of variation  sum of squares  degree of freedom mean sum of squares  \
0          regression      178.839594                  2           89.419797   
1               error      151.410406                  9           16.823378   
2               total      330.250000                 11                       

  variance Ratio  
0                 
1        5.31521  
2                 
    observed  calculated     error
0        100  100.461432 -0.461432
1        110  103.113969  6.886031
2        105  102.256422  2.743578
3         94   94.920932 -0.920932
4         95   96.364914 -1.364914
5         99  100.967971 -1.967971
6        104  105.415498 -1.415498
7        108  108.810000 -0.810000
8        105  105.259968 -0.259968
9         98  105.806454 -7.806454
10       105  104.713481  0.286519
11       110  104.908959  5.091041


In [ ]:
import scipy.stats
p = 1-scipy.stats.f.cdf(f,k-1,n-k)
if f<p:
  print("accept")
else:
  print('reject')


reject


Test For Individual Parameters

In [ ]:
import scipy.stats as ss
mse2=sse/9
seb0=np.sqrt(invxtx[0][0]*mse2)
seb1=np.sqrt(invxtx[1][1]*mse2)
seb2=np.sqrt(invxtx[2][2]*mse2)
tcb0=beta[0]/seb0
tcb1=beta[1]/seb1
tcb2=beta[2]/seb2
dt={
    "Predictor":['B0','B1','B2'],
    "Coefficient":[beta[0],beta[1],beta[2]],
    "Standard Error":[seb0,seb1,seb2],
    "t":[beta[0]/seb0,beta[1]/seb1,beta[2]/seb2]
}
print(pd.DataFrame(dt))

  Predictor  Coefficient  Standard Error         t
0        B0   133.460482       26.229411  5.088200
1        B1    -1.248503        0.444634 -2.807937
2        B2    -0.351008        0.455165 -0.771167


In [ ]:
los=0.05
ttab=ss.t.ppf(1-los/2,9)


In [ ]:
for i in range(len(dt['t'])):
  if abs(dt['t'][i])<ttab:
    print(f'B {i} is not contributing to model')
  else:
    print(f'B {i} is contibuting to model')


B 0 is contibuting to model
B 1 is contibuting to model
B 2 is not contributing to model


In [ ]:
xx=np.array(list(map(int,input().split()))).reshape(3,3)




1 2 3 4 5 6 7 8 9
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


In [ ]:
# 1 9 62 1 8 58 1 7 64 
# 1 1 1 1 1 1 1 1 1 1 1 1
# 9 8 7 14 12 10 7 4 6 5 7 6
# 62 58 64 60 63 57 55 56 59 61 57 60


In [ ]:
def trans(m):
  x=m.shape
  mt=np.zeros(x,int)
  for i in range(len(m[0])):
    for j in range(len(m[0])):
      mt[i][j]=m[j][i]
  return mt


In [ ]:
m_t=trans(xx)
print(m_t)
print(xx)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
def det_(m):
  return 
