<a href="https://colab.research.google.com/github/ali786-1/Computational-Statistics/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import numpy as np
x=[]
n=int(input("Enter No of variables"))
for i in range(n):
  a=[float(i) for i in input().split()]
  x.append(a)
x=np.transpose(x)



Enter No of variables3
90 90 60 60 30
60 90 60 60 30
90 30 60 90 30


In [98]:
x_mu=x-np.mean(x,axis=0)
x_mu


array([[ 24.,   0.,  30.],
       [ 24.,  30., -30.],
       [ -6.,   0.,   0.],
       [ -6.,   0.,  30.],
       [-36., -30., -30.]])

In [99]:
c=np.dot(np.transpose(x_mu),x_mu)/len(x)
c

array([[504., 360., 180.],
       [360., 360.,   0.],
       [180.,   0., 720.]])

In [100]:
eigen_values,eigen_vectors=np.linalg.eig(c)
sort_id=eigen_values.argsort()[::-1]
eigen_values=eigen_values[sort_id]
eigen_vectors=np.transpose(eigen_vectors[:,sort_id])
print(eigen_values,(eigen_vectors))

[910.06995304 629.11038668  44.81966028] [[-0.65580225 -0.4291978  -0.62105769]
 [-0.3859988  -0.51636642  0.7644414 ]
 [ 0.6487899  -0.74104991 -0.17296443]]


In [101]:
import pandas as pd
eig_tot=sum(eigen_values)
c_p=[]
threshold=int(input("Enter Threshold"))
num=0
c=1
for i in range(n):
  num+=(eigen_values[i])
  c_p.append(np.round(((num/eig_tot)*100),2))
  if c_p[-1]<=threshold:
    c+=1
print(c_p)

d={
    "Principal Components":[f'z{i+1}' for i in range(n)],
   "Variance Explained":eigen_values,
   "Cummilative Proportion of Total VAriance":c_p
}
data=pd.DataFrame(d)
data

Enter Threshold95
[57.45, 97.17, 100.0]


Principal Components  Variance Explained  \
0                   z1          910.069953   
1                   z2          629.110387   
2                   z3           44.819660   

   Cummilative Proportion of Total VAriance  
0                                     57.45  
1                                     97.17  
2                                    100.00

In [112]:
z=np.dot(eigen_vectors[:c],x.T)
for i in range(len(z)):
  n=0
  for j in z[i]:
    if j<0:
      n+=1
  if n>=len(z[i])//2:
    z[i]=z[i]*-1
z



array([[140.6692628 , 116.28173533, 102.36346447, 120.99519515,
         51.18173223],
       [ -3.07784927,  58.27962721,   8.27542884, -14.65781313,
          4.13771442]])

In [113]:
x_=x.T
result={}
for i in range(len(x_)):
  result[f'x{i+1}'] = x_[i]
for i in range(len(z)):
  result[f'z{i+1}']=z[i]
j=pd.DataFrame(result)
j


x1    x2    x3          z1         z2
0  90.0  60.0  90.0  140.669263  -3.077849
1  90.0  90.0  30.0  116.281735  58.279627
2  60.0  60.0  60.0  102.363464   8.275429
3  60.0  60.0  90.0  120.995195 -14.657813
4  30.0  30.0  30.0   51.181732   4.137714

In [114]:
print(eigen_vectors)
print(x_[0]*eigen)

[[-0.65580225 -0.4291978  -0.62105769]
 [-0.3859988  -0.51636642  0.7644414 ]
 [ 0.6487899  -0.74104991 -0.17296443]]
